In [1]:
#vector
import numpy as np
v = np.array([1,2,3])
print(v)

[1 2 3]


In [2]:
v1=np.array([3,4,5])
print(np.sum(v1))

12


In [3]:
s=v-v1
print(v)
print(v1)
print(s)

[1 2 3]
[3 4 5]
[-2 -2 -2]


In [4]:
p = v**2
print(p)

[1 4 9]


In [5]:
dot = np.dot(v,v1)
print(dot)

26


In [6]:
#matrices
A= np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [7]:
print(A.shape)

(2, 3)


In [8]:
B=np.array([[1,1,1],[2,2,3]])
c=A+B
print(A)
print(B)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 3]]
[[2 3 4]
 [6 7 9]]


In [9]:
#list
prices = [100,200,400]
prices.append('a')
print(prices)
prices.remove('a')
print(prices)
prices.append(200)
print(prices)
prices.remove(200)
print(prices)

[100, 200, 400, 'a']
[100, 200, 400]
[100, 200, 400, 200]
[100, 400, 200]


In [10]:
prices=list()
prices.append(('p1',45))
prices.append(('p2',100))
print(prices)

[('p1', 45), ('p2', 100)]


In [11]:
s = [1,2,3,4,3,3,3]
print(s)
print(set(s))

[1, 2, 3, 4, 3, 3, 3]
{1, 2, 3, 4}


In [12]:
#lambda function

#div(a): a/2

#def div(a):
#   return a/2
div = lambda x:x/2

div(10)

5.0

In [13]:
prices.append(('p3',10))
prices.append(('p4',55))
print(prices)

[('p1', 45), ('p2', 100), ('p3', 10), ('p4', 55)]


In [14]:
prices.sort()

In [15]:
print(prices)

[('p1', 45), ('p2', 100), ('p3', 10), ('p4', 55)]


In [17]:
prices.append(('a1',54))
prices.sort()
print(prices)

[('a1', 54), ('p1', 45), ('p2', 100), ('p3', 10), ('p4', 55)]


In [18]:
prices.sort(key=lambda x:x[1])
print(prices)

[('p3', 10), ('p1', 45), ('a1', 54), ('p4', 55), ('p2', 100)]


In [20]:
a=[(1,2,3),(4,5,9),(7,8,9)]
print(a)

[(1, 2, 3), (4, 5, 9), (7, 8, 9)]


In [22]:
o=[row[-1] for row in a]
print(o)

[3, 9, 9]


In [ ]:
#max count
mx= max